services:
  spring-lms-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: qiraht/spring-ticketing-order-api:latest
    container_name: spring-ticketing-order-api
    ports:
      - "${PORT:-8080}:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - PORT=${PORT:-8080}
      ## Mysql
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    restart: always